"""Create logs and threat_alerts core tables

Revision ID: c5811ad5e888
Revises: 
Create Date: 2026-08-23 13:46:19.042940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5811ad5e888'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_destination_ip'), 'logs', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_logs_event_type'), 'logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_logs_source_ip'), 'logs', ['source_ip'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_table('threat_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('threat_type', sa.String(length=100), nullable=False),
    sa.Column('threat_score', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_alerts_source_ip'), 'threat_alerts', ['source_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_alerts_source_ip'), table_name='threat_alerts')
    op.drop_table('threat_alerts')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index(op.f('ix_logs_source_ip'), table_name='logs')
    op.drop_index(op.f('ix_logs_event_type'), table_name='logs')
    op.drop_index(op.f('ix_logs_destination_ip'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
